### ISSUE TITLE
Java interface proxies do not respect optional arguments in methods

### ISSUE THREAD

**Issue by eladb** [awslabs/jsii#175]
They should convert optional members into method overloads.

Repro:

```ts
export interface InterfaceWithOptional {
  myMethod(arg1: string, optionalArg2: number?);
}
```

Package to java and the generated interface will include two methods (one with a single argument and one with two) but the proxy will only contain a single method. Compilation will fail.

**Comment by RomainMuller** [comment]
This will likely be true for constructors, as well.

**Comment by eladb** [comment]
Constructors [are covered](https://github.com/awslabs/jsii/blob/master/packages/jsii-pacmak/lib/generator.ts#L180) by [`generateOverloadsForMethodsWithOptionals`](https://github.com/awslabs/jsii/blob/46f17714f22fde54f4add209141daddd2dadf0ad/packages/jsii-pacmak/lib/generator.ts#L27)
