### ISSUE TITLE
Forces me to use a license field

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/jsii#195]
I don't want to license my package, however jsii forces me to or it will not build:

```
Error: /home/local/ANT/huijbers/Workspaces/CDKAnalytics/src/CDKAmznResources/packages/cdk-amzn-resources/package.json has "license" UNLICENSED, which doesn't appear to be a valid SPDX identifier
```

- unlicensed or UNLICENSED are not accepted
- The package is marked `private: true` so I think jsii has no business checking my license at all.

**Comment by rix0rrr** [comment]
`LicenseRef-LICENSE` is also not accepted.

I seem to be forced to license my code under some Open Source license

`Proprietary` is also not accepted.

**Comment by rix0rrr** [comment]
Is this code not wrong? 

https://github.com/awslabs/jsii/blob/master/packages/jsii/lib/package-metadata.ts#L5

Should that not have been use of this package? https://www.npmjs.com/package/spdx-expression-validate

**Comment by RomainMuller** [comment]
`UNLICENSED` is accepted by the rewrite I have in a PR. It was an oversight in the current version. But yes, DPDX license identifier or `UNLICENSED` is all that is valid

**Comment by RomainMuller** [comment]
Resolving. `UNLICENSED` is now an option.

**Comment by very-doge-wow** [comment]
How can we add custom licenses? We have a custom propietary license which must be used to be compliant.
This is in the format `LincenseRef-XXX`, but is rejected by jsii.
