### ISSUE TITLE
Documentation doesn't mention inherited members

### ISSUE THREAD

**Issue by RomainMuller** [awslabs/jsii#196]
The documentation generated by `jsii-pacmak` does not include references to inherited members that were not overridden. This makes the documentation appear a little confusing and makes discovery of a full API surface more complicated.

For example, the `s3.Bucket` class inherits most of it's interesting members from `s3.BucketRef`, but this is not entirely obvious (particularly to a newcomer). The documentation should include inherited members as part of a class' documentation in one way or another.

**Comment by eladb** [comment]
I agree, we should include the full docs for inherited members!

**Comment by Doug-AWS** [comment]
Does that mean we'll also show all Construct members for all that extend Construct, such as BucketRef?

**Comment by eladb** [comment]
Yes, ideally indicating where these methods came from...
