### ISSUE TITLE
JSII seems to not prevent a read-write property from being downgraded to read-only

### ISSUE THREAD

**Issue by RomainMuller** [awslabs/jsii#199]
@moofish32 suffered an occurrence in awslabs/aws-cdk#538 where `jsii` did not correctly capture that a read-write property was being incorrectly implemented as `readonly`, causing the Java bindings to fail building due to a missing implementation of the setter (property was inherited from an interface).

**Comment by moofish32** [comment]
reproduction - https://github.com/moofish32/jsii-bug-repros (currently just on master)

**Comment by RomainMuller** [comment]
I have already confirmed that the issue would not be present in the re-write in #188. I have added a test demonstrating that.

**Comment by RomainMuller** [comment]
I have also added a fix on the current implementation of `jsii` (#201).
