### ISSUE TITLE
[ERROR] Configuration outdir not being used

### ISSUE THREAD

**Issue by seawatts** [awslabs/jsii#213]
When running jsii with `outdir` set to `build` it puts all the `.js` and `.d.ts` files inline into their current folders.

**Comment by seawatts** [comment]
Interesting, is there any plans to change that. Personally I'm not a huge fan because I feel like it clutters those directories unless you explicitly ignore them from your ide (i'm using vscode)

**Comment by eladb** [comment]
We were talking about adding an ability to customize the typescript compiler inputs/outputs via the jsii configuration. At the moment, it's quite [rigid](https://github.com/awslabs/jsii/blob/master/packages/jsii/lib/compiler.ts#L159)

**Comment by eladb** [comment]
Dup #203
