### ISSUE TITLE
Optional `any` is typed as a required `any`.

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/jsii#230]
Originally reported here:

https://github.com/awslabs/aws-cdk/issues/714

The issue is that the declaration was:

```
interface Permission {
    sourceAccount?: any;
}
```

Which got translated into the following JSII:

```
        {
          "name": "sourceAccount",
          "type": {
            "primitive": "any"
          }
        },
```

I.e., the "optional" part of it got lost.

**Comment by RomainMuller** [comment]
I found the bug's cause (compiler would not consider the `declaration.questionMark`, and would only report as optional the union types including `null` and/or `undefined`). This actually makes me wonder if we should treat all `any` as `optional` (aka - if the type is `any`, then it is `optional any`)?

**Comment by RomainMuller** [comment]
Well the PR #237 includes code to make `any` optional everywhere it is found (because that is how TypeScript thinks of it).

**Comment by eladb** [comment]
But what happens if there’s an “any” argument in the middle of a signature? Optional arguments are only allowed at the end.

**Comment by RomainMuller** [comment]
Well - `optional` is a type attribute, not a `parameter` attribute. In the general sense, it denotes nullability (and in fact, TypeScript lets you put optional arguments in any place you want).

**Comment by eladb** [comment]
<img width="737" alt="screen shot 2018-09-21 at 12 38 57 am" src="https://user-images.githubusercontent.com/598796/45848355-c709ec00-bd36-11e8-813a-17eb5a402b49.png">

**Comment by rix0rrr** [comment]
Yes, there is (somewhat) of a difference between `x?: l2` and `x: l2 | undefined`

**Comment by RomainMuller** [comment]
That is in large parts because `jsii` models `optional` as a type attribute, and not as a parameter attribute...
