### ISSUE TITLE
Singleton enums are not typed properly

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/jsii#231]
An enum with a single value is type-inferred by TSC to be some thing that we have no support for.

I looked into it for a bit, it's not trivial to extend it though.

**Comment by RomainMuller** [comment]
@rix0rrr do you have a concrete case where a single-entry enum is used?

**Comment by rix0rrr** [comment]
I had one but I removed it (because obviously we can do without)

**Comment by jogold** [comment]
An example in `@aws-cdk/aws-ec2` is the [type of VPN connection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpn-gateway.html#cfn-ec2-vpngateway-type). Currently, the only valid value is `ipsec.1`.

See the discussion with @eladb here https://github.com/awslabs/aws-cdk/pull/1899#discussion_r260818446
