### ISSUE TITLE
Java: method overloads are not generated (regression)

### ISSUE THREAD

**Issue by eladb** [awslabs/jsii#233]
Oddly, method overloads are no longer generated (see CDK `Bucket` constructor, and `Bucket.grantRead` examples)

**Comment by RomainMuller** [comment]
One thing I see already is that in the constructor of `Bucket`, `props` is not modelled as `optional`, despite it carries a default value. This is a bug in the `jsii` compiler.

**Comment by rix0rrr** [comment]
We should prohibit overloads at the jsii level anyway.

Golang doesn't support them, for example.

**Comment by rix0rrr** [comment]
Nor Rust, should we ever want to target that.

**Comment by RomainMuller** [comment]
They're not really overrides... We're making overrides without the trailing optional arguments to make Javaists' lives nicer.

**Comment by eladb** [comment]
Exactly. So languages that do not support them can only generate the method and allow nulls to be passed for optional arguments

**Comment by rix0rrr** [comment]
Oh I see, overloads as an implementation mechanism. That's fine.
