### ISSUE TITLE
Properties versus parameters/setter methods is inconsistent 

### ISSUE THREAD

**Issue by fulghum** [awslabs/jsii#280]
properties versus parameters/setter methods – seems inconsistent from an outside view.  Have to think about the right way to set each piece of data and not immediately clear why some settings are exposed different ways. 

(root cause might really be the CDK codebase, and not jsii generation)

**Comment by eladb** [comment]
This is not a jsii issue. It's actually case-by-case in the CDK. Let's open specific issues for APIs that we feel are inconsistent.
