### ISSUE TITLE
Ensure Data Types have a "pure" inheritance tree

### ISSUE THREAD

**Issue by dstufft** [awslabs/jsii#287]
Data Types and "Normal" interfaces need to have distinct inheritance trees for the Python generated code to function. IOW, a data type can't inherent from a non data type, and a non data type can't inherit from a data type.

https://github.com/awslabs/jsii/pull/271 should solve the case where a data type cannot inherit from a non data type, however it's still the case that a non data type can inherit from a data type. IOW this currently is accepted:

```typescript

export interface SomeProps {
    foo: str
}

export interface ISomething extends SomeProps {
    bar(): void;
}
```

However, that could would cause an error in Python, because a "normal" interface cannot inherit from a data type, so we should reject that in the JSII compiler.

**Comment by rix0rrr** [comment]
This should already be the case. I'm fairly sure I added checks to this effect. No?

**Comment by rix0rrr** [comment]
Can't seem to find a test for it though ;(

**Comment by dstufft** [comment]
My memory is that the checks only existed for things that start with ``I``, but that things that don't start with ``I`` could still exhibit this problem.

**Comment by RomainMuller** [comment]
Existing check (`jsii` already rejects):
- [X] An interface extending another one which is _not_ a struct, _cannot_ be a struct.

Missing checks (`jsii` will happily proceed):
- [ ] A class may not implement a struct interface
- [ ] A regular interface may not implement a struct
