### ISSUE TITLE
jsii: Add "install" integration tests

### ISSUE THREAD

**Issue by eladb** [awslabs/jsii#314]
To avoid issues like https://github.com/awslabs/jsii/pull/313, we should include some integration tests in our pipeline that "npm installs" jsii from tarballs. This can be achieved either by "npm install js/*.tgz" or by using [verdaccio](https://github.com/verdaccio/verdaccio).

**Comment by sam-goodwin** [comment]
I think we can re-use a bunch of the existing tests - add a JSII 'target' (or something) environment variable to switch between behavior. Saves re-doing veradccio and less boilerplate such as installing, checking canary mode, etc.

**Comment by eladb** [comment]
Can we extract the verdaccio stuff to a scripts that’s reusable between Jsii and cdk tests?
