### ISSUE TITLE
kernel: return type for unexported types

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/jsii#345]
Someone reported a failing case over email, where we were returning a `Construct` to Java, which should have been a particular L1 class.

Key insight: the type we construct a proxy for depends on the requested type. Compliance test:

```ts
export class PublicClass {
    hello(): void;
}

export interface IPublicInterface {
    bye(): void;
}

export class InbetweenClass extends PublicClass {
}

class PrivateClass extends InbetweenClass implements IPublicInterface {
    public hello() {
        process.stdout.write('Hello\n');
    }

    public bye() {
        process.stdout.write('Bye\n');
    }
}

export class Constructors {
    public static makeClass(): PublicClass {
        return new PrivateClass();
    }

    public static makeInterface(): IPublicInterface {
        return new PrivateClass();
    }
}
```

Given the same object instance:

* `Constructors.makeClass()` should return a proxy object for `InbetweenClass`.
* `Constructors.makeInterface()` should return a proxy object for `IPublicInterface`.

Given:

* The actual type (`PrivateClass`)
* The requested type (`PublicClass` vs. `IPublicInterface`)
* The inheritance hierarchy

We should be returning the most specific type on the inheritance path between actual and requested that is itself `exported`.

**Comment by rix0rrr** [comment]
An issue implementing this might be that the kernel does not have type information on unexported types, so it will only have:

* Requested type `PublicClass`
* Actual type `PrivateClass`

And it for sure cannot return `PrivateClass` to a JSII consumer.

**Comment by RomainMuller** [comment]
I reckon https://github.com/awslabs/jsii/blob/0301e305aab027f6350b3051a5d2b08b6fe7cbb5/packages/jsii-kernel/lib/kernel.ts#L964 should be changed so it accepts to return the current runtime type if it is assignable to the requested type. That would widely increase the scope of what can be down-casted in languages like Java.
