### ISSUE TITLE
Setting up a development environment in order to be able to contribute

### ISSUE THREAD

**Issue by floehopper** [awslabs/jsii#354]
First of all I tried following the contribution guide, but got the following error:

```
$ eval $(aws ecr get-login --no-include-email)
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
$ IMAGE=260708760616.dkr.ecr.us-east-1.amazonaws.com/superchain:latest
$ docker pull ${IMAGE}
Error response from daemon: Get https://260708760616.dkr.ecr.us-east-1.amazonaws.com/v2/superchain/manifests/latest: no basic auth credentials
```

Reading around a bit, I came across [this comment on the awslabs/aws-cdk repo](https://github.com/awslabs/aws-cdk/issues/474#issuecomment-414601917) which said:

> This will work only for members of the awslabs organization, unfortunately, as the superchain repository and image are private.

Am I correct in assuming that the error I'm seeing is because I'm not a member of the awslabs GitHub (?) organization?

I noticed the awslabs/aws-cdk repo now has a `Dockerfile` and has updated its contributing guide to use this rather than the superchain repo & image: https://github.com/awslabs/aws-cdk/blob/1d705e7143134574c33f6c6f221a8a549f318efa/CONTRIBUTING.md#full-docker-build.

Presumably my best bet is to create a `Dockerfile` along the lines of the one in the awslabs/aws-cdk repo...? Any advice would be very welcome!

PS: I also had a go at trying to get the `build.sh` & `install.sh` scripts to run on my local (Mac OSX) machine by installing the various dependencies, but I ran into a bunch of problems. This doesn't seem like a very sensible approach so I've abandoned it.

**Comment by eladb** [comment]
Here's how you can build "superchain":

Clone [this repo](https://github.com/awslabs/aws-delivlib):

```console
$ git clone git@github.com:awslabs/aws-delivlib.git
```

Build superchain (it will take some time):

```console
$ cd aws-delivlib/superchain
$ docker build -t superchain .
```

**Comment by floehopper** [comment]
@eladb Thanks! That worked!

**Comment by eladb** [comment]
Any chance I can bug you to send a PR for our contributing guide to that affect?

**Comment by floehopper** [comment]
Sure - no problem 👍

**Comment by eladb** [comment]
Also, would you like to set up some time to chat over video on this work? The repo documentation is very scarce and I'd love to give you some context and pointers on how to tackle this... It's quite hairy...
