### ISSUE TITLE
Indicate what versions of the JSII an assembly is targeting

### ISSUE THREAD

**Issue by dstufft** [awslabs/jsii#357]
Currently when emitting a JSII using project Python has to include a dependency on the jsii python runtime library. However there's no indication what versions of this runtime library a particular assembly (or output of pacmak at least) is intended to be targeting. This means that we can only emit an unversioned dependency on just ``jsii``.

It would be ideal to have some mechanism to derive what the supported JSII runtime version(s) are.

**Comment by RomainMuller** [comment]
The code generator *has* to be coded against a particular version of the runtime library, and this means it has authority to determine what version of the runtime it needs to depend on. Typically, the version will match that of `jsii-pacmak`.

**Comment by fulghum** [comment]
@dstufft and @garnaat – does this resolve your concern around versioning/compatibility?  Or do you see a concern that requires deeper validation?

**Comment by fulghum** [comment]
Confirmed with Mitch that this will do what we need.
