### ISSUE TITLE
Enumerate the allowed doc properties and their meaning

### ISSUE THREAD

**Issue by dstufft** [awslabs/jsii#358]
Currently it appears that the documentation objects that an Assembly can contain are largely freeform Key -> Value fields. It would be really great if their was instead a defined set of keys that were acceptable with some documentation explaining what each of those defined set of keys were. That would make it a lot easier to translate into other language's doc syntax.

**Comment by eladb** [comment]
@rix0rrr is formalizing this as we speak under #415
