### ISSUE TITLE
Check that there are not static and non-static members with the same name

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/jsii#427]
It's definitely not allowed in Java, but probably is allowed in TypeScript, so jsii should guard against it.

**Comment by skinny85** [comment]
Yes, it's definitely allowed in TypeScript. I ran into this doing the rename of all L1 classes to add the `Cfn` prefix - I had an `isReference` static method and an `isReference` property in the same class. The pacmak build for C# was the only thing that caught it.

**Comment by rix0rrr** [comment]
While we're at it, we should guard against having statics with the same name as a class we're inheriting from.

**Comment by rix0rrr** [comment]
Okay I'm not sure about the second one actually. Java allows this:

```java
class Henk {
  public static void henk() {
    System.out.println("Inherited henk");
  }
}

class Main extends Henk {
  public static void main(String[] args) {
    Main.henk();
  }
}
```

C# does too:

```cs
using System;

class Henk {
  public static void henk() {
    Console.WriteLine ("Inherited Henk");
  }
}

class MainClass : Henk {
  public static void Main (string[] args) {
    MainClass.henk();
  }
}
```

Works the same in TypeScript:

```ts
class Henk {
  public static henk() {
    console.log('Inherited henk');
  }
}

class Main extends Henk {

}

Main.henk();
```

I don't see any problem.
