### ISSUE TITLE
Internal class erasure does not implement interface in derived

### ISSUE THREAD

**Issue by eladb** [awslabs/jsii#487]
Repro:

```ts
export interface IExternal { }
class Internal implements IExternal { }
export class Derived extends Internal { }
```

I am expecting the jsii spec for `Derived` to implement `IExternal` as an interface.

**Comment by skinny85** [comment]
Oh, is this actually allowed in JSII?

I thought I remember seeing an error that all superclasses of an exported class need to be exported as well... but if that's not the case, that actually changes some design choices I made in the CDK :).

**Comment by eladb** [comment]
Yes, we recently added this support, but obvsiouly fucked up.

**Comment by eladb** [comment]
I have a fix. Will send a PR shortly
