### ISSUE TITLE
.NET Generator: Explicitly implement interface properties and methods

### ISSUE THREAD

**Issue by assyadh** [awslabs/jsii#560]
Right now we are implicitly implementing the interface properties and methods.

We need to explicitly write each signature, so that If a class implements two interfaces methods/properties with the same signature, there is no clash:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation

**Comment by RomainMuller** [comment]
I don't think the clash is material in fact, as Javascript wouldn't allow this scenario (a given prototype may only have ONE implementation for a given member name). So I think this is probably overkill.

The node runtime will basically guarantee that those cases imply that both interfaces' same-named method have the same semantics.
